"""reconcile course and semester schema drift with models

Revision ID: 25e18d29e845
Revises: 80d7ff9376bc
Create Date: 2026-08-12 18:19:18.530088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e18d29e845'
down_revision: Union[str, Sequence[str], None] = '80d7ff9376bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'classroom',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('courses', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'DROPPED', 'ARCHIVED', name='coursestatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_courses_semester_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('uq_active_course_code_per_semester'), table_name='courses', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.create_index('ix_courses_semester_id', 'courses', ['semester_id'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_index('uq_courses_active_semester_code', 'courses', ['semester_id', 'course_code'], unique=True, postgresql_where=sa.text("is_deleted = false AND status = 'ACTIVE'"))
    op.drop_constraint(op.f('courses_user_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'user_id')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('semesters', 'status',
               existing_type=postgresql.ENUM('UPCOMING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='semesterstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('semesters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('semesters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('semesters', 'status',
               existing_type=postgresql.ENUM('UPCOMING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='semesterstatus'),
               server_default=sa.text("'UPCOMING'::semesterstatus"),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.add_column('courses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('courses_user_id_fkey'), 'courses', 'users', ['user_id'], ['id'])
    op.drop_index('uq_courses_active_semester_code', table_name='courses', postgresql_where=sa.text("is_deleted = false AND status = 'ACTIVE'"))
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_semester_id', table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_index(op.f('uq_active_course_code_per_semester'), 'courses', ['semester_id', 'course_code'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_index(op.f('idx_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.alter_column('courses', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'DROPPED', 'ARCHIVED', name='coursestatus'),
               server_default=sa.text("'ACTIVE'::coursestatus"),
               existing_nullable=False)
    op.alter_column('courses', 'classroom',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
