"""add document file metadata

Revision ID: 3b4e98b64361
Revises: 17a40adcc6ad
Create Date: 2026-07-19 02:12:47.892934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4e98b64361'
down_revision: Union[str, Sequence[str], None] = '17a40adcc6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_course_id'), 'documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_unique_constraint(None, 'documents', ['file_path'])
    op.drop_constraint(op.f('documents_course_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_course_id_fkey'), 'documents', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_course_id'), table_name='documents')
    op.alter_column('documents', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
